<a href="https://colab.research.google.com/github/hmao2/PGSS2023/blob/main/PGSS_CS_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

Mounted at /gdrive

In [33]:
%load_ext rpy2.ipython

In [30]:
import pandas as pd
df = pd.read_csv("/gdrive/MyDrive/PGSS/PGSS - CS Lab Course/Week 1/Week01/iris.csv", header = None)
df.columns = ["Petal.Length", "Petal.Width", "Sepal.Length", "Sepal.width", "Species"]
df

     Petal.Length  Petal.Width  Sepal.Length  Sepal.width         Species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

Lets try to read in some data from Google Sheets

In [31]:
# https://docs.google.com/spreadsheets/d/1VK-Zs72ebK6ddwvDYFN2cA04PDTbVLXJeylmdJ7OxkM/edit#gid=0

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

worksheet = gc.open('PGSS2023').sheet1

# get_all_values gives a list of rows.
rows = worksheet.get_all_values()
print(rows)

[['First Name', 'Last Name', 'Andrew ID', 'Github', 'Role', '', 'Non-Andrew Email', 'Height'], ['Parth', 'Parikh', 'pcparikh', 'ParthParikh04', 'Student', '', 'parthparikh04@gmail.com', '5\'6"'], ['Sooraj', 'Tharumia', 'stharumi', 'SoorajTharumia', 'Student', '', 'sendsooraj@gmail.com', '5\'5"'], ['Yeana', 'Kim', 'ygkim', 'ygkim19', 'Student', '', 'pkyeanakim@gmail.com', '5\'1"'], ['Darren ', 'Wang', 'darrenwa', 'DPnimo11', 'Student', '', 'dpnimo11@gmail.com', '5\'8"'], ['Felix', 'Yang', 'fsyang', 'fsyang05', 'Student', '', 'fsyang05@gmail.com', "5'8"], ['Helen', 'Mao', 'hmao2', 'SavagePancake', 'Student', '', 'helenmao2006@gmail.com', "5'2"], ['Ben', 'Nguyen', 'aqnguyen', 'BenjieN07', 'student', '', 'nguyenquangduyan.us@gmail.com', '5\'7"'], ['Edward', 'Mei', 'emei2', 'cmuedmei', 'Student', '', 'meis201601@gmail.com', "5'8''"], ['Jonathan', 'Barsotti', 'jbarsott', 'bwitishjack', 'Student', '', 'jackbarsotti06@gmail.com', '5\'11"'], ['Lihini', 'Ranaweera', 'lranawee', 'lihiniranaweera', 'Student', '', 'lihini.ranaweera@icloud.com', "5'2''"], ['Karina', 'Chan-van der Helm', 'kchanvan', 'KCvdH', 'Student', '', 'kchan-vanderhelm@sch.org', '5\'8"'], ['Carter', 'Rogers', 'ctrogers', 'carterrrogers', 'Student', '', 'carterrog@icloud.com', "5'6"], ['Yanwei', 'Liu', 'yanweil', 'yanwe1', 'Student', '', 'yyaliu102@gmail.com', '5\'1"'], ['Izabella ', 'Gurreonero', 'igurreon', 'izmunsta', 'Student', '', 'kiara31306@icloud.com', "5'5"], ['Olina', 'Mukherjee', 'omukherj', 'olimu', 'student', '', 'olina.mukherjee@gmail.com', "5'2"], ['Kamya', 'Rajesh', 'karajesh', 'kamya-rajesh', 'student', '', 'kam.r2576@gmail.com', '5\'8"'], ['Jessica', 'Hou', 'jhou3', 'piginpink', 'student', '', 'jessicahow123@gmail.com', '5\'2"'], ['John', 'Beeson', 'jbeeson', 'John-Beeson', 'Student', '', 'jbrambeeson@gmail.com', '5\'10"'], ['Kofi', 'Anokye', 'kanokye', '', 'Student', '', 'kofianokye1864@gmail.com', '5\'8"'], ['Antony', 'Tomy', 'atomy', 'antonytomy', 'Student', '', 'antonytomy17@gmail.com', "5 11'"], ['Krystof', 'Purtell', 'krystofp', 'krystofpurtell', 'TA', '', 'krystofp@sas.upenn.edu', "6'2''"], ['Liam', 'Hower', 'ljhower', 'superpi2', 'TA', '', 'superpi2.Aa.Xx@gmail.com', '6\'0"']]

In [32]:
# Convert to a DataFrame and render.
import pandas as pd

df2 = pd.DataFrame.from_records(rows[1:])
df2.columns = rows[0]
df2

,First Name,Last Name,Andrew ID,Github,Role,,Non-Andrew Email,Height
0,Parth,Parikh,pcparikh,ParthParikh04,Student,,parthparikh04@gmail.com,"5'6"""
1,Sooraj,Tharumia,stharumi,SoorajTharumia,Student,,sendsooraj@gmail.com,"5'5"""
2,Yeana,Kim,ygkim,ygkim19,Student,,pkyeanakim@gmail.com,"5'1"""
3,Darren,Wang,darrenwa,DPnimo11,Student,,dpnimo11@gmail.com,"5'8"""
4,Felix,Yang,fsyang,fsyang05,Student,,fsyang05@gmail.com,5'8
5,Helen,Mao,hmao2,SavagePancake,Student,,helenmao2006@gmail.com,5'2
6,Ben,Nguyen,aqnguyen,BenjieN07,student,,nguyenquangduyan.us@gmail.com,"5'7"""
7,Edward,Mei,emei2,cmuedmei,Student,,meis201601@gmail.com,5'8''
8,Jonathan,Barsotti,jbarsott,bwitishjack,Student,,jackbarsotti06@gmail.com,"5'11"""
9,Lihini,Ranaweera,lranawee,lihiniranaweera,Student,,lihini.ranaweera@icloud.com,5'2''
10,Karina,Chan-van der Helm,kchanvan,KCvdH,Student,,kchan-vanderhelm@sch.org,"5'8"""
11,Carter,Rogers,ctrogers,carterrrogers,Student,,carterrog@icloud.com,5'6
12,Yanwei,Liu,yanweil,yanwe1,Student,,yyaliu102@gmail.com,"5'1"""
13,Izabella,Gurreonero,igurreon,izmunsta,Student,,kiara31306@icloud.com,5'5
14,Olina,Mukherjee,omukherj,olimu,student,,olina.mukherjee@gmail.com,5'2
15,Kamya,Rajesh,karajesh,kamya-rajesh,student,,kam.r2576@gmail.com,"5'8"""
16,Jessica,Hou,jhou3,piginpink,student,,jessicahow123@gmail.com,"5'2"""
17,John,Beeson,jbeeson,John-Beeson,Student,,jbrambeeson@gmail.com,"5'10"""
18,Kofi,Anokye,kanokye,,Student,,kofianokye1864@gmail.com,"5'8"""
19,Antony,Tomy,atomy,antonytomy,Student,,antonytomy17@gmail.com,5 11'
20,Krystof,Purtell,krystofp,krystofpurtell,TA,,krystofp@sas.upenn.edu,6'2''
21,Liam,Hower,ljhower,superpi2,TA,,superpi2.Aa.Xx@gmail.com,"6'0"""